# Generated by Django 3.2.7 on 2021-10-03 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_auto_20211002_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong_lanmu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_lanmu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lanmu',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lanmu_children', to='Blog.lanmu'),
        ),
    ]
