# Generated by Django 3.2.7 on 2021-10-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_pinglun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinglun',
            name='text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
