# Generated by Django 3.2.7 on 2021-10-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_pinglun_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinglun',
            old_name='belong_art',
            new_name='belong',
        ),
    ]
