# Generated by Django 4.0 on 2021-12-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_favourite_like_payorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayOrder',
        ),
    ]
