# Generated by Django 3.2.7 on 2022-02-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_delete_payorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nickName',
            new_name='username',
        ),
    ]
