# Generated by Django 3.2.7 on 2022-02-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_rename_nickname_userinfo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='nickName',
        ),
    ]
